### ISSUE TITLE
Add to awesome-awesomeness

### ISSUE THREAD

**Issue by westurner** [yoloseem/awesome-sphinxdoc#3]
See: https://github.com/bayandin/awesome-awesomeness/pull/100

**Comment by yoloseem** [comment]
https://github.com/bayandin/awesome-awesomeness/pull/100 seems that requires rebase to resolve conflicts

**Comment by m1guelpf** [comment]
@westurner As I said in the PR, it needs manual merge. If you want to speed up the merge, please fix it and ping me

**Comment by yoloseem** [comment]
closing it since #100 is merged. thanks!
