### ISSUE TITLE
I would like to contribute.

### ISSUE THREAD

**Issue by kaymccormick** [yoloseem/awesome-sphinxdoc#46]
I would like to help with this list. I just created an awesome-restructuredtext list but it occured to me that a list might exist for sphinxdoc. I'm not sure if i should simply add to your list, or have a separate list, since sphinx is not the focus of my list.

I also noted that there are outstanding pull requests. let me know how I can help.

**Comment by yoloseem** [comment]
if you find anything good to be listed in this curation, feel free to send a pull request. many thanks!
